version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-Trial}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"     
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,lambda
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=${DATA_DIR- }
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Required for Lambda WebAPi to work
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /var/lib/localstack:exec,mode=600
    networks:
      - local-network
    privileged: true # Required for Lambda function to run in Docker

networks:
  local-network:
    name: local-network
