#
PUT {{urlRoot}}/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "User1",
  "score": 61,
  "userId": "1",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###
        
PUT {{urlRoot}}/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "User2",
  "score": 625,
  "userId": "2",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###

PUT {{urlRoot}}/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "User3",
  "score": 100,
  "userId": "3",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###

PUT {{urlRoot}}/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "User2",
  "score": 700,
  "userId": "3",
  "game": "TABLETENNIS",
  "yearMonth": "2023-09"
}

###

PUT {{urlRoot}}/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "User1",
  "score": 900,
  "userId": "1",
  "game": "TABLETENNIS",
  "yearMonth": "2023-09"
}

###

GET {{urlRoot}}/LeaderBoard/topscores/CHESS/2023-09
accept: */*
Content-Type: application/json

###

GET {{urlRoot}}/LeaderBoard/topscores/TABLETENNIS/2023-09
accept: */*
Content-Type: application/json