#
PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello1",
  "score": 61,
  "userId": "1"
}

###
        
PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
"userName": "Hello2",
"score": 625,
"userId": "2"
}

###

PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello3",
  "score": 100,
  "userId": "3"
}

###

GET https://localhost:5001/LeaderBoard/topscores
accept: */*
Content-Type: application/json