#
PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello1",
  "score": 61,
  "userId": "1",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###
        
PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello2",
  "score": 625,
  "userId": "2",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###

PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello3",
  "score": 100,
  "userId": "3",
  "game": "CHESS",
  "yearMonth": "2023-09"
}

###

PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello3",
  "score": 100,
  "userId": "3",
  "game": "TABLETENNIS",
  "yearMonth": "2023-09"
}

###

PUT https://localhost:5001/LeaderBoard/scores
accept: */*
Content-Type: application/json

{
  "userName": "Hello1",
  "score": 500,
  "userId": "1",
  "game": "TABLETENNIS",
  "yearMonth": "2023-09"
}

###

GET https://localhost:5001/LeaderBoard/topscores/CHESS/2023-09
accept: */*
Content-Type: application/json

###

GET https://localhost:5001/LeaderBoard/topscores/TABLETENNIS/2023-09
accept: */*
Content-Type: application/json